commit all task
Illia1927/HomeWorkJPA pull request #1
Opened 2019-01-20 18:10 UTC by Illia1927

2019-01-21 14:10 UTC, Dimitriy1 commented on src/main/java/mateAcademy/EntityManagerHolder.java
> +}
An extra line should be in your file

2019-01-21 14:53 UTC, DmitriyLitvin requested changes

2019-01-21 14:53 UTC, Dimitriy1 commented on src/main/java/mateAcademy/Main.java
> +}
You have used bilder, it's ok, but I think that It's not your idea, try to use your own brain!

2019-01-21 14:53 UTC, Dimitriy1 commented on src/main/java/mateAcademy/PatientServlet.java
> +}
This file isn't important for your programme. Why did you put it here?

2019-01-21 14:53 UTC, Dimitriy1 commented on pom.xml
>  </project>
An extra line should be in your file

2019-01-21 14:53 UTC, Dimitriy1 commented on src/main/java/mateAcademy/test/Test.java
> +
I don't want to check if it works, but when you оverride method toString() ,and in your case that patient has many tests and test has one patient - relation one to many, and in method  toString()  from class patient you returned tests and in method toString()  from class test you returned patient -it can be reason of stack overflow exception,so check it!

2019-01-21 14:53 UTC, Dimitriy1 commented on src/main/resources/META-INF/persistence.xml
> +</persistence>
An extra line should be in your file

2019-01-21 14:53 UTC, Dimitriy1 commented on src/main/java/mateAcademy/device/Device.java
> +
delete this extra line

2019-01-21 14:59 UTC, Dimitriy1 commented on src/main/java/mateAcademy/EntityManagerHolder.java
> +}
And Why have you written method private EntityManagerHolder() {
    }? Why do you need it here ?

2019-01-21 23:44 UTC, DmitriyLitvin approved these changes

2019-01-21 23:44 UTC, Dimitriy1 commented on src/main/java/mateAcademy/device/Device.java
> +    public void setId(long id) {
this setter must have Long id - not primitive as you have used, and change it everywere where you have used primitive instead of wrapper type

2019-01-21 23:44 UTC, Dimitriy1 commented on src/main/java/mateAcademy/service/impl/TestServiceImpl.java
> +
empty line between class declaration and field, remove it

2019-01-21 23:44 UTC, Dimitriy1 commented on src/main/java/mateAcademy/dao/impl/TestDaoImpl.java
> +
empty line between class declaration and constructor or method or field should be deleted everywere were you have written code in such way

2019-01-22 00:08 UTC, DmitriyLitvin requested changes

2019-01-22 00:08 UTC, Dimitriy1 commented on src/main/java/mateAcademy/test/Test.java
> +
empty line

2019-01-22 00:08 UTC, Dimitriy1 commented on src/main/java/mateAcademy/test/Test.java
> +
empty line, and change it everywere were you will see it

2019-01-22 07:27 UTC, boroda4436 requested changes

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/EntityManagerHolder.java
> +}
@Dimitriy1 First: this not a method, this is constructor. Second: read about Singleton pattern private constructor

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/accessory/Accessory.java
> +import javax.persistence.*;
@Illia1927 Don't use * import

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/accessory/PhotomoterAccessory.java
> +}
@Illia1927 add at least two fields to sub class

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/accessory/UltrasonicAccessory.java
> +}
@Illia1927 add at least two fields to sub class

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/dao/GrudDao.java
> +public interface GrudDao<T, ID extends Serializable> {
@Illia1927 Grud or Crud?

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/dao/GrudDao.java
> +    T made(T entity);
@Illia1927 let's use standard names (create, not made)

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/dao/impl/TestDaoImpl.java
> +
@Illia1927 please, fix it

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/dao/impl/TestDaoImpl.java
> +                .createQuery("from Test", Test.class).getResultList();
@Illia1927 Have you tested this?
@Dimitriy1 Have tried to run this HW? Everything is working ok?

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/device/Device.java
> +    public void setId(long id) {
@Illia1927 please, fix it

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/test/Test.java
> +    public static Test getTest(typeOfTest testType) {
@Illia1927 in future, please move this to some factory class, as we have do in patterns HW. This not required now

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/test/Test.java
> +    public static enum typeOfTest {
@Illia1927 start naming with leading letter

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/test/Test.java
> +
@Illia1927 have you tested this?
@Dimitriy1 please, try to run this whole HW too

2019-01-22 07:27 UTC, boroda4436 commented on src/main/java/mateAcademy/utill/HibernateUtill.java
> +public class HibernateUtill {
@Illia1927 if you are using EntityManagerHolder, please remove this class

2019-01-23 15:44 UTC, boroda4436 requested changes

2019-01-23 15:44 UTC, boroda4436 commented on src/main/java/mateAcademy/accessory/Accessory.java
> +import javax.persistence.*;
@Illia1927 not fixed)

2019-01-23 15:44 UTC, boroda4436 commented on src/main/java/mateAcademy/device/Device.java
> +import javax.persistence.*;
@Illia1927 star import

2019-01-23 15:44 UTC, boroda4436 commented on src/main/java/mateAcademy/patients/Patient.java
> +import javax.persistence.*;
@Illia1927

2019-01-23 15:44 UTC, boroda4436 commented on src/main/java/mateAcademy/test/Test.java
> +import javax.persistence.*;
@Illia1927

2019-01-24 08:02 UTC, boroda4436 approved these changes
LGTM

2019-01-24 10:00 UTC, merged

2019-01-27 01:30 UTC, Dimitriy1 commented on src/main/java/mateAcademy/EntityManagerHolder.java
> +}
@boroda4436 Sorry, yes I agree that this class must be a Singleton, But constructor is a special method in class, or group of instructions that initialize an object. It depends on definition